replicaCount: 1

image:
  imageName: reviewReaper:1.0
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.


imagePullSecrets:
  - name: registrysecret


serviceAccount:
  create: true
  annotations: {}
  name: "reviewreaper"
  clusterRoleName: cluster-admin

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80


resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
