namespace_prefixes:
  - review
  - feature

# Retention defined in days. May be additionally tuned in hours
# TODO: Andd hours in config for retention fine-tuning.
retention:
  days: 1
  hours: 2

# deletion_batch_size: 1
# deletion_nap_seconds: 1

annotation_key: delete_after
delete_by_release: false

deletion_windows:
  not_before: "00:00"
  not_after:  "23:59"
  week_days:
    - Sun
    - Mon
